DivInf/Controllers/ConsultaController.cs
using DivInf.Core.DTOs;
using DivInf.Core.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace DivInf.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class ConsultaController : Controller
    {
        private readonly IConsultaService _consultaService;

        public ConsultaController(IConsultaService consultaService)
        {
            _consultaService = consultaService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            try
            {
                ViewData["CostoSortParm"] = sortOrder == "costo" ? "costoDesc" : "costo";
                ViewData["fechaSortParm"] = sortOrder == "fecha" ? "fechaDesc" : "fecha";
                ViewData["CurrentFilter"] = searchString;

                var listConsultas = await _consultaService.GetConsultas();

                if (!String.IsNullOrEmpty(searchString))
                {
                    listConsultas = await _consultaService.GetConsultas(searchString);
                }

                switch (sortOrder)
                {
                    case "costo":
                        listConsultas = listConsultas.OrderBy(x => x.Costo);
                        break;
                    case "costoDesc":
                        listConsultas = listConsultas.OrderByDescending(x => x.Costo);
                        break;
                    case "fechaDesc":
                        listConsultas = listConsultas.OrderByDescending(x => x.Fecha);
                        break;
                    default:
                        listConsultas = listConsultas.OrderBy(x => x.Fecha);
                        break;
                }

                return View(listConsultas);
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("Create")]
        public async Task<IActionResult> Create([FromForm] ConsultaDTO consulta)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var addConsulta = await _consultaService.AddConsulta(consulta);
                    if (addConsulta)
                    {
                        TempData["mensaje"] = "La consulta se ha creado correctamente.";
                        return RedirectToAction("Index");
                    }
                }
                TempData["mensaje"] = "La consulta no se ha creado correctamente, matricula o historia clinica incorrecta.";
                return View();
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpGet("edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id == null || id == 0)
                {
                    return NotFound();
                }

                var consulta = await _consultaService.GetConsultaById(id);

                if (consulta == null)
                {
                    return NotFound();
                }

                return View(consulta);
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpPost("edit")]
        public async Task<IActionResult> EditConsulta([FromForm] ConsultaUpdateDTO consulta)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var updateConsulta = await _consultaService.UpdateConsulta(consulta);

                    if (updateConsulta)
                    {
                        TempData["mensaje"] = "La consulta se ha actualizado correctamente.";
                        return RedirectToAction("Index");
                    }
                }
                TempData["mensaje"] = "La consulta no se pudo actualizar correctamente, matricula o historia clinica incorrecta.";
                return View();
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpGet("delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null || id == 0)
                {
                    return NotFound();
                }

                var paciente = await _consultaService.GetConsultaById(id);

                if (paciente == null)
                {
                    return NotFound();
                }

                return View(paciente);
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpPost("delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var medico = await _consultaService.GetConsultaById(id);

                if (medico == null)
                {
                    return NotFound();
                }

                await _consultaService.DeleteConsulta(id);

                TempData["mensaje"] = "La consulta se ha eliminado correctamente.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }
    }
}

DivInf/Views/Consulta/Create.cshtml
@model DivInf.Core.DTOs.ConsultaDTO

@{
    ViewData["Title"] = "Crear consulta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" arial-label="close">
                <span arial-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-6">
            <h3>Agregar consulta</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Fecha" class="control-label"></label>
                    <input asp-for="Fecha" class="form-control" />
                    <span asp-validation-for="Fecha" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Matricula" class="control-label"></label>
                    <input asp-for="Matricula" class="form-control" />
                    <span asp-validation-for="Matricula" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Tipo" class="control-label"></label>
                    <input asp-for="Tipo" class="form-control" />
                    <span asp-validation-for="Tipo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Costo" class="control-label"></label>
                    <input asp-for="Costo" class="form-control" />
                    <span asp-validation-for="Costo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="CostoMaterial" class="control-label"></label>
                    <input asp-for="CostoMaterial" class="form-control" />
                    <span asp-validation-for="CostoMaterial" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="HistoriaClinica" class="control-label"></label>
                    <input asp-for="HistoriaClinica" class="form-control" />
                    <span asp-validation-for="HistoriaClinica" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Agregar consulta" class="btn btn-primary" />
                    <a asp-controller="Consulta" asp-action="Index" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DivInf/Views/Consulta/Delete.cshtml
@model DivInf.Core.DTOs.ConsultaDTO

@{
    ViewData["Title"] = "Eliminar consulta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" arial-label="close">
                <span arial-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-6">
            <h3>Eliminar consulta</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Delete">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Fecha" class="control-label"></label>
                    <input asp-for="Fecha" class="form-control" disabled/>
                    <span asp-validation-for="Fecha" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Matricula" class="control-label"></label>
                    <input asp-for="Matricula" class="form-control" disabled/>
                    <span asp-validation-for="Matricula" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Tipo" class="control-label"></label>
                    <input asp-for="Tipo" class="form-control" disabled/>
                    <span asp-validation-for="Tipo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Costo" class="control-label"></label>
                    <input asp-for="Costo" class="form-control" disabled/>
                    <span asp-validation-for="Costo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" disabled/>
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="CostoMaterial" class="control-label"></label>
                    <input asp-for="CostoMaterial" class="form-control" disabled/>
                    <span asp-validation-for="CostoMaterial" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="HistoriaClinica" class="control-label"></label>
                    <input asp-for="HistoriaClinica" class="form-control" disabled/>
                    <span asp-validation-for="HistoriaClinica" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Eliminar consulta" class="btn btn-primary" />
                    <a asp-controller="Consulta" asp-action="Index" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DivInf/Views/Consulta/Edit.cshtml
@model DivInf.Core.DTOs.ConsultaDTO

@{
    ViewData["Title"] = "Editar consulta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" arial-label="close">
                <span arial-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-6">
            <h3>Editar consulta</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="EditConsulta">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />

                <div class="form-group">
                    <label asp-for="Fecha" class="control-label"></label>
                    <input asp-for="Fecha" class="form-control" />
                    <span asp-validation-for="Fecha" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Matricula" class="control-label"></label>
                    <input asp-for="Matricula" class="form-control" />
                    <span asp-validation-for="Matricula" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Tipo" class="control-label"></label>
                    <input asp-for="Tipo" class="form-control" />
                    <span asp-validation-for="Tipo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Costo" class="control-label"></label>
                    <input asp-for="Costo" class="form-control" />
                    <span asp-validation-for="Costo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="CostoMaterial" class="control-label"></label>
                    <input asp-for="CostoMaterial" class="form-control" />
                    <span asp-validation-for="CostoMaterial" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="HistoriaClinica" class="control-label"></label>
                    <input asp-for="HistoriaClinica" class="form-control" />
                    <span asp-validation-for="HistoriaClinica" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Editar consulta" class="btn btn-primary" />
                    <a asp-controller="Consulta" asp-action="Index" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DivInf/Views/Consulta/Index.cshtml
@model IEnumerable<DivInf.Core.DTOs.ConsultaDTO>

@{
    ViewData["Title"] = "Consulta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" arial-label="close">
                <span arial-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-3">
            <h2>Lista de consultas</h2>
        </div>
        <div class="col-sm-6">
            <form asp-action="Index" method="get">
                <div class="form-actions text-black font-weight-bold">
                    <p>
                        Filtro: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
                        <input type="submit" value="Buscar" class="btn btn-primary" />
                        <a asp-action="Index" class="btn btn-light">Ver todos los consultas</a>
                    </p>
                </div>
            </form>
        </div>
        <div class="col-sm-3 justify-content-end">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Consulta">Agregar nuevo consultas</a>
        </div>
    </div>

    <div class="row container">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead class="table-light">
                    <tr>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewData["fechaSortParm"]">@Html.DisplayNameFor(x => x.Fecha)</a>
                        </th>
                        <th>Matricula</th>
                        <th>Tipo</th>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewData["CostoSortParm"]">@Html.DisplayNameFor(x => x.Costo)</a>
                        </th>
                        <th>Descripción</th>
                        <th>Costo material</th>
                        <th>Historia clinica</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.Fecha</td>
                        <td>@item.Matricula</td>
                        <td>@item.Tipo</td>
                        <td>@item.Costo</td>
                        <td>@item.Descripcion</td>
                        <td>@item.CostoMaterial</td>
                        <td>@item.HistoriaClinica</td>
                        <td>
                            <a asp-controller="Consulta" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Editar</a>
                            <a asp-controller="Consulta" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <h3 class="text-black text-danger">No hay consultas</h3>
        }
    </div>
</div>