DivInf/Controllers/PacienteController.cs
using DivInf.Core.DTOs;
using DivInf.Core.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace DivInf.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class PacienteController : Controller
    {
        private readonly IPacienteService _pacienteService;

        public PacienteController(IPacienteService pacienteService)
        {
            _pacienteService = pacienteService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            try
            {
                ViewData["NombreSortParm"] = sortOrder == "nombre" ? "nombreDesc" : "nombre";
                ViewData["HistoriaClinicaSortParm"] = sortOrder == "historiaClinica" ? "historiaClinicaDesc" : "historiaClinica";
                ViewData["CurrentFilter"] = searchString;

                var listPacientes = await _pacienteService.GetPacientes();

                if (!String.IsNullOrEmpty(searchString))
                {
                    listPacientes = await _pacienteService.GetPacientes(searchString);
                }

                switch (sortOrder)
                {
                    case "nombre":
                        listPacientes = listPacientes.OrderBy(x => x.Nombre);
                        break;
                    case "nombreDesc":
                        listPacientes = listPacientes.OrderByDescending(x => x.Nombre);
                        break;
                    case "historiaClinicaDesc":
                        listPacientes = listPacientes.OrderByDescending(x => x.HistoriaClinica);
                        break;
                    default:
                        listPacientes = listPacientes.OrderBy(x => x.HistoriaClinica);
                        break;
                }

                return View(listPacientes);
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("Create")]
        public async Task<IActionResult> Create([FromForm] PacienteDTO paciente)
        {
            try
            {
                var pacienteExist = await _pacienteService.GetPacienteByHistoriaClinica(paciente.HistoriaClinica);

                if (pacienteExist != null)
                {
                    TempData["mensaje"] = "Ya existe un paciente con esa historia clinica.";
                }
                else if (ModelState.IsValid)
                {
                    await _pacienteService.AddPaciente(paciente);

                    TempData["mensaje"] = "El paciente se ha creado correctamente.";
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpGet("edit")]
        public async Task<IActionResult> Edit(int? historiaClinica)
        {
            try
            {
                if (historiaClinica == null || historiaClinica == 0)
                {
                    return NotFound();
                }

                var paciente = await _pacienteService.GetPacienteByHistoriaClinica(historiaClinica);

                if (paciente == null)
                {
                    return NotFound();
                }

                return View(paciente);
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpPost("edit")]
        public async Task<IActionResult> Edit([FromForm] PacienteUpdateDTO paciente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _pacienteService.UpdatePaciente(paciente);

                    TempData["mensaje"] = "El paciente se ha actualizado correctamente.";
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpGet("delete/{historiaClinica}")]
        public async Task<IActionResult> Delete(int? historiaClinica)
        {
            try
            {
                if (historiaClinica == null || historiaClinica == 0)
                {
                    return NotFound();
                }

                var paciente = await _pacienteService.GetPacienteByHistoriaClinica(historiaClinica);

                if (paciente == null)
                {
                    return NotFound();
                }

                return View(paciente);
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpPost("delete/{historiaClinica}")]
        public async Task<IActionResult> Delete(int historiaClinica)
        {
            try
            {
                var medico = await _pacienteService.GetPacienteByHistoriaClinica(historiaClinica);

                if (medico == null)
                {
                    return NotFound();
                }

                await _pacienteService.DeletePaciente(historiaClinica);

                TempData["mensaje"] = "El paciente se ha eliminado correctamente.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }
    }
}

DivInf/Views/Paciente/Create.cshtml
@model DivInf.Core.DTOs.PacienteDTO

@{
    ViewData["Title"] = "Crear paciente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" arial-label="close">
                <span arial-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-6">
            <h3>Agregar paciente</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="HistoriaClinica" class="control-label"></label>
                    <input asp-for="HistoriaClinica" class="form-control" />
                    <span asp-validation-for="HistoriaClinica" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Agregar paciente" class="btn btn-primary" />
                    <a asp-controller="Paciente" asp-action="Index" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DivInf/Views/Paciente/Delete.cshtml
@model DivInf.Core.DTOs.PacienteDTO

@{
    ViewData["Title"] = "Eliminar paciente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" arial-label="close">
                <span arial-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-6">
            <h3>Eliminar paciente</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Delete">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" disabled />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="HistoriaClinica" class="control-label"></label>
                    <input asp-for="HistoriaClinica" class="form-control" disabled />
                    <span asp-validation-for="HistoriaClinica" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Eliminar paciente" class="btn btn-primary" />
                    <a asp-controller="Paciente" asp-action="Index" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DivInf/Views/Paciente/Edit.cshtml
@model DivInf.Core.DTOs.PacienteDTO

@{
    ViewData["Title"] = "Editar paciente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" arial-label="close">
                <span arial-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-6">
            <h3>Editar paciente</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="HistoriaClinica" class="control-label"></label>
                    <input asp-for="HistoriaClinica" class="form-control" />
                    <span asp-validation-for="HistoriaClinica" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Editar paciente" class="btn btn-primary" />
                    <a asp-controller="Paciente" asp-action="Index" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DivInf/Views/Paciente/Index.cshtml
@model IEnumerable<DivInf.Core.DTOs.PacienteDTO>

@{
    ViewData["Title"] = "Paciente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" arial-label="close">
                <span arial-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-3">
            <h2>Lista de pacientes</h2>
        </div>
        <div class="col-sm-6">
            <form asp-action="Index" method="get">
                <div class="form-actions text-black font-weight-bold">
                    <p>
                        Filtro: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
                        <input type="submit" value="Buscar" class="btn btn-primary" />
                        <a asp-action="Index" class="btn btn-light">Ver todos los pacientes</a>
                    </p>
                </div>
            </form>
        </div>
        <div class="col-sm-3 justify-content-end">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Paciente">Agregar nuevo paciente</a>
        </div>
    </div>

    <div class="row container">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead class="table-light">
                    <tr>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewData["NombreSortParm"]">@Html.DisplayNameFor(x => x.Nombre)</a>
                        </th>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewData["HistoriaClinicaSortParm"]">@Html.DisplayNameFor(x => x.HistoriaClinica)</a>
                        </th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Nombre</td>
                            <td>@item.HistoriaClinica</td>
                            <td>
                                <a asp-controller="Paciente" asp-action="Edit" asp-route-historiaclinica="@item.HistoriaClinica" class="btn btn-warning">Editar</a>
                                <a asp-controller="Paciente" asp-action="Delete" asp-route-historiaclinica="@item.HistoriaClinica" class="btn btn-danger">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <h3 class="text-black text-danger">No hay pacientes</h3>
        }
    </div>
</div>