DivInf/Controllers/MedicoController.cs
using DivInf.Core.DTOs;
using DivInf.Core.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace DivInf.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class MedicoController : Controller
    {
        private readonly IMedicoService _medicoService;

        public MedicoController(IMedicoService medicoService)
        {
            _medicoService = medicoService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            try
            {
                ViewData["EspecialidadSortParm"] = String.IsNullOrEmpty(sortOrder) ? "especialidadDesc" : "especialidad";
                ViewData["NombreSortParm"] = sortOrder == "nombre" ? "nombreDesc" : "nombre";
                ViewData["MatriculaSortParm"] = sortOrder == "matricula" ? "matriculaDesc" : "matricula";
                ViewData["CurrentFilter"] = searchString;

                var listMedicos = await _medicoService.GetMedicos();

                if (!String.IsNullOrEmpty(searchString))
                {
                    listMedicos = await _medicoService.GetMedicos(searchString);
                }

                switch (sortOrder)
                {
                    case "especialidadDesc":
                        listMedicos = listMedicos.OrderByDescending(x => x.Especialidad);
                        break;
                    case "nombre":
                        listMedicos = listMedicos.OrderBy(x => x.Nombre);
                        break;
                    case "nombreDesc":
                        listMedicos = listMedicos.OrderByDescending(x => x.Nombre);
                        break;
                    case "especialidad":
                        listMedicos = listMedicos.OrderBy(x => x.Especialidad);
                        break;
                    case "matriculaDesc":
                        listMedicos = listMedicos.OrderByDescending(x => x.Matricula);
                        break;
                    default:
                        listMedicos = listMedicos.OrderBy(x => x.Matricula);
                        break;
                }

                return View(listMedicos);
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("Create")]
        public async Task<IActionResult> Create([FromForm] MedicoDTO medico)
        {
            try
            {
                var medicoExist = await _medicoService.GetMedicoByMatricula(medico.Matricula);

                if (medicoExist != null)
                {
                    TempData["mensaje"] = "Ya existe un medico con esa matricula.";
                }
                else if (ModelState.IsValid)
                {
                    await _medicoService.AddMedico(medico);

                    TempData["mensaje"] = "El medico se ha creado correctamente.";
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpGet("edit")]
        public async Task<IActionResult> Edit(int? matricula)
        {
            try
            {
                if (matricula == null || matricula == 0)
                {
                    return NotFound();
                }

                var medico = await _medicoService.GetMedicoByMatricula(matricula);

                if (medico == null)
                {
                    return NotFound();
                }

                return View(medico);
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpPost("edit")]
        public async Task<IActionResult> Edit([FromForm] MedicoUpdateDTO medico)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _medicoService.UpdateMedico(medico);

                    TempData["mensaje"] = "El medico se ha actualizado correctamente.";
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpGet("delete/{matricula}")]
        public async Task<IActionResult> Delete(int? matricula)
        {
            try
            {
                if (matricula == null || matricula == 0)
                {
                    return NotFound();
                }

                var medico = await _medicoService.GetMedicoByMatricula(matricula);

                if (medico == null)
                {
                    return NotFound();
                }

                return View(medico);
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }

        [HttpPost("delete/{matricula}")]
        public async Task<IActionResult> Delete(int matricula)
        {
            try
            {
                var medico = await _medicoService.GetMedicoByMatricula(matricula);

                if (medico == null)
                {
                    return NotFound();
                }

                await _medicoService.DeleteMedico(matricula);

                TempData["mensaje"] = "El medico se ha eliminado correctamente.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }
    }
}

DivInf/Views/Medico/Create.cshtml
@model DivInf.Core.DTOs.MedicoDTO

@{
    ViewData["Title"] = "Crear medico";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" arial-label="close">
                <span arial-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-6">
            <h3>Agregar medico</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Especialidad" class="control-label"></label>
                    <input asp-for="Especialidad" class="form-control" />
                    <span asp-validation-for="Especialidad" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Matricula" class="control-label"></label>
                    <input asp-for="Matricula" class="form-control" />
                    <span asp-validation-for="Matricula" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Agregar medico" class="btn btn-primary" />
                    <a asp-controller="Medico" asp-action="Index" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DivInf/Views/Medico/Delete.cshtml
@model DivInf.Core.DTOs.MedicoDTO

@{
    ViewData["Title"] = "Eliminar medico";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" arial-label="close">
                <span arial-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-6">
            <h3>Eliminar medico</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Delete">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" disabled />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Especialidad" class="control-label"></label>
                    <input asp-for="Especialidad" class="form-control" disabled />
                    <span asp-validation-for="Especialidad" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Matricula" class="control-label"></label>
                    <input asp-for="Matricula" class="form-control" disabled />
                    <span asp-validation-for="Matricula" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Eliminar medico" class="btn btn-primary" />
                    <a asp-controller="Medico" asp-action="Index" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DivInf/Views/Medico/Edit.cshtml
@model DivInf.Core.DTOs.MedicoDTO

@{
    ViewData["Title"] = "Editar medico";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" arial-label="close">
                <span arial-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-6">
            <h3>Editar medico</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Especialidad" class="control-label"></label>
                    <input asp-for="Especialidad" class="form-control" />
                    <span asp-validation-for="Especialidad" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Matricula" class="control-label"></label>
                    <input asp-for="Matricula" class="form-control" />
                    <span asp-validation-for="Matricula" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Editar medico" class="btn btn-primary" />
                    <a asp-controller="Medico" asp-action="Index" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DivInf/Views/Medico/Index.cshtml
@model IEnumerable<DivInf.Core.DTOs.MedicoDTO>

@{
    ViewData["Title"] = "Medico";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" arial-label="close">
                <span arial-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-3">
            <h2>Lista de medicos</h2>
        </div>
        <div class="col-sm-6">
            <form asp-action="Index" method="get">
                <div class="form-actions text-black font-weight-bold">
                    <p>
                        Filtro: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
                        <input type="submit" value="Buscar" class="btn btn-primary" />
                        <a asp-action="Index" class="btn btn-light">Ver todos los medicos</a>
                    </p>
                </div>
            </form>
        </div>
        <div class="col-sm-3 justify-content-end">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Medico">Agregar nuevo medico</a>
        </div>
    </div>

    <div class="row container">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead class="table-light">
                    <tr>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewData["MatriculaSortParm"]">@Html.DisplayNameFor(x => x.Matricula)</a>
                        </th>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewData["NombreSortParm"]">@Html.DisplayNameFor(x => x.Nombre)</a>
                        </th>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewData["EspecialidadSortParm"]">@Html.DisplayNameFor(x => x.Especialidad)</a>
                        </th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Matricula</td>
                            <td>@item.Nombre</td>
                            <td>@item.Especialidad</td>
                            <td>
                                <a asp-controller="Medico" asp-action="Edit" asp-route-matricula="@item.Matricula" class="btn btn-warning">Editar</a>
                                <a asp-controller="Medico" asp-action="Delete" asp-route-matricula="@item.Matricula" class="btn btn-danger">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <h3 class="text-black text-danger">No hay medicos</h3>
        }
    </div>
</div>